export const userConstants = {
  LIST_USER_REQUEST: "LIST_USER_REQUEST",
  LIST_USER_SUCCESS: "LIST_USER_SUCCESS",
  ACTIVATE_USER_REQUEST: "ACTIVATE_USER_REQUEST",
  ACTIVATE_USER_SUCCESS: "ACTIVATE_USER_SUCCESS",
  DEACTIVATE_USER_REQUEST: "DEACTIVATE_USER_REQUEST",
  DEACTIVATE_USER_SUCCESS: "DEACTIVATE_USER_SUCCESS",
};
