"""add department

Revision ID: a65fdf1637e8
Revises: 1de75dc4ac5c
Create Date: 2020-02-01 16:45:00.956228

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'a65fdf1637e8'
down_revision = '1de75dc4ac5c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('department',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_department_id'), 'department', ['id'], unique=False)
    op.add_column('product', sa.Column('department_id', sa.Integer(), nullable=True))
    op.alter_column('product', 'category_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
    op.alter_column('product', 'cost',
               existing_type=mysql.DECIMAL(precision=10, scale=2),
               nullable=True)
    op.alter_column('product', 'expiration_count',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
    op.alter_column('product', 'physical_count',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
    op.create_index(op.f('ix_product_department_id'), 'product', ['department_id'], unique=False)
    op.create_foreign_key(None, 'product', 'department', ['department_id'], ['id'])
    op.alter_column('user', 'is_active',
               existing_type=mysql.TINYINT(display_width=1),
               type_=sa.Boolean(),
               existing_nullable=False)
    op.alter_column('user', 'is_superuser',
               existing_type=mysql.TINYINT(display_width=1),
               type_=sa.Boolean(),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'is_superuser',
               existing_type=sa.Boolean(),
               type_=mysql.TINYINT(display_width=1),
               existing_nullable=False)
    op.alter_column('user', 'is_active',
               existing_type=sa.Boolean(),
               type_=mysql.TINYINT(display_width=1),
               existing_nullable=False)
    op.drop_constraint(None, 'product', type_='foreignkey')
    op.drop_index(op.f('ix_product_department_id'), table_name='product')
    op.alter_column('product', 'physical_count',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
    op.alter_column('product', 'expiration_count',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
    op.alter_column('product', 'cost',
               existing_type=mysql.DECIMAL(precision=10, scale=2),
               nullable=False)
    op.alter_column('product', 'category_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
    op.drop_column('product', 'department_id')
    op.drop_index(op.f('ix_department_id'), table_name='department')
    op.drop_table('department')
    # ### end Alembic commands ###
